### ISSUE TITLE
Review LR2

### ISSUE THREAD

**Issue by steminist-ua** [N3wm1e/Lb#2]
**не коректна структура сторінки.** За завданням необхідно було саме блокам з контентом задати налаштування кольорів та позицій, а не створювати окремі порожні... 

Якщо вже є необхідність "викручуватися" таким методом (хоча наголошую, що в цьому завданні такої необхідності немає), тоді краще використовувати `div` замість `section`

https://github.com/N3wm1e/Lb/blob/eac00b75da367740ae66eae3700f6b99929eec33/lb2/index.html#L11-L18

**Comment by steminist-ua** [comment]
**потрібно використовувати відносний шлях до зображення** 

https://github.com/N3wm1e/Lb/blob/eac00b75da367740ae66eae3700f6b99929eec33/lb2/index.html#L25-L27

**Comment by steminist-ua** [comment]
**Шрифти необхідно підключати на самому початку css (scss) файлу, без використання селектору**. В даному випадку, перед селектором body

https://github.com/N3wm1e/Lb/blob/eac00b75da367740ae66eae3700f6b99929eec33/lb2/style.scss#L1-L4

**правильний код:** 

```css
@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');

body{    
    font-family: 'Roboto', sans-serif;
}
```
